# Generated by Django 2.2.12 on 2020-10-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='iCV_Nation/images/defaults.jpg', upload_to='iCV_Nation/images')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=30)),
                ('abc', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('contact', models.CharField(default='0900', max_length=14)),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(default='iCV_Nation/images/defaults.jpg', upload_to='iCV_Nation/images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=30)),
                ('product_price', models.IntegerField(default='000')),
                ('product_description', models.CharField(default='', max_length=300)),
                ('product_image', models.ImageField(default='iCV_Nation/images/defaults.jpg', upload_to='iCV_Nation/images')),
                ('category_type', models.CharField(default='', max_length=30)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='users.Category')),
            ],
        ),
    ]
