"""
Django settings for shopApp project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a19iuqe=z4uyq%g+%8hn$i%flq*qz0j9z6c1+c@%m_c+vntgcz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'rest_framework',
    'knox',
    'product',
    'crypto',
    'notify',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iCV_Nation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iCV_Nation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'iCVNation',
        'USER': 'postgres',
        'PASSWORD': '123',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    
]
# STATIC_ROOT= os.path.join(BASE_DIR,"static")
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SERVER_URL='http://127.0.0.1:8000'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        # 'knox.auth.TokenAuthentication',
    ]
}
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST_USER = 'asimraza336@gmail.com'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_SERVER = 'smtp.gmail.com'
# EMAIL_HOST_PASSWORD = 'Anonymous1'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = False
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend',
# EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
# EMAIL_HOST = 'smtp.sendgrid.net',
# EMAIL_HOST_USER = 'hk43341@gmail.com',
# EMAIL_HOST_PASSWORD = 'Asimraza123456789',
# EMAIL_PORT = 587,
# EMAIL_USE_TLS = True,
# SENDGRID_API_KEY = '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',


# SENDGRID_API_KEY = get_env_variable('SEND_GRID_API_KEY')

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# SENDGRID_API_KEY = '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'

# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_HOST_USER = 'asimraza336@gmail.com'
# EMAIL_HOST_PASSWORD = 'Anonymous1'
# EMAIL_PORT = 465
# EMAIL_USE_TLS = True
# # EMAIL_USE_SSL = False


# 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'
# EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"

# SENDGRID_API_KEY = os.environ[SENDGRID_API_KEY]

# SENDGRID_SANDBOX_MODE_IN_DEBUG = True

# EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
# SENDGRID_API_KEY='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'

# SENDGRID_SANDBOX_MODE_IN_DEBUG=True
# SENDGRID_ECHO_TO_STDOUT=True

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com',
EMAIL_HOST = 'mail.esquall.com'
EMAIL_HOST_USER = 'asim.raza@esquall.com'     
# EMAIL_HOST_USER = 'asimraz336@gmail.com'
EMAIL_HOST_PASSWORD = 'x^=ew+-ick$^'    
# EMAIL_HOST_PASSWORD = 'Anonymous1'                             
EMAIL_PORT = 26
# # This did the trick
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")
                     







# EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
# SENDGRID_SANDBOX_MODE_IN_DEBUG = False
# FROM_EMAIL = 'asim.raza@esquall.com' # replace with your address
# SENDGRID_API_KEY = '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'