# Generated by Django 3.1.2 on 2020-10-27 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=30)),
                ('product_price', models.IntegerField(default='000')),
                ('product_description', models.CharField(default='', max_length=300)),
                ('product_image', models.ImageField(default='iCV_Nation/images/defaults.jpg', upload_to='iCV_Nation/images')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='product.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
