# Generated by Django 3.1.2 on 2020-10-28 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_auto_20201027_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_number', models.IntegerField(default='1')),
                ('product_quantity', models.IntegerField(default='000')),
                ('product_price_total', models.IntegerField(default='000')),
                ('no_of_products_in_cart', models.IntegerField()),
                ('total_items_in_cart', models.IntegerField(default='1')),
                ('shipping_cost', models.IntegerField(default='5')),
                ('total_cost_of_order', models.IntegerField(default='000')),
                ('order_confirmation_status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
