# Generated by Django 3.1.2 on 2020-10-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20201029_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addtional_requirements',
            field=models.TextField(default='additional_requirements'),
        ),
    ]
