# Generated by Django 3.1.2 on 2020-10-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_order_addtional_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
    ]
