# Generated by Django 3.1.2 on 2020-10-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20201029_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('I', 'Initiated'), ('A', 'Accepted'), ('CBD', 'Canceled By Driver'), ('D', 'Delivered')], default='Initiated', max_length=200),
        ),
    ]
