# Generated by Django 3.1.2 on 2020-10-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addtional_requirements',
            new_name='additional_requirements',
        ),
    ]
