# Generated by Django 3.1.2 on 2020-10-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201027_1428'),
        ('product', '0021_auto_20201029_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='message', max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('Driver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
            ],
        ),
    ]
