# Generated by Django 3.1.2 on 2020-11-02 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='order',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='product.order'),
        ),
    ]
