# Generated by Django 3.1.2 on 2020-11-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_notifications_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='order',
            new_name='Order',
        ),
    ]
